platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!
# 官方Cocoapods源
source 'https://github.com/CocoaPods/Specs.git'

target 'LMPNPBox_Example' do
  pod 'LMPNPBox', :path => '../'
  
  #Data
  pod 'ObjectMapper'
  #UI
  pod 'SnapKit'
  #network
  pod 'Alamofire'
  

  target 'LMPNPBox_Tests' do
    inherit! :search_paths
  end
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
      if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
